services:
  reverse_proxy:
    image: nginx:1.27
    container_name: kintone_revproxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/server.pem:/server.pem:ro
      - ./certs/server-key.pem:/server-key.pem:ro
    ports:
      - 443:443
    command: ['nginx-debug', '-g', 'daemon off;']

