services:
  reverse_proxy:
    build:
      context: .
    image: nginx_revproxy
    container_name: kintone_revproxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./example.com.pem:/example.com.pem
      - ./example.com-key.pem:/example.com-key.pem
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=example.com
