services:
  reverse_proxy:
    image: nginx:1.27
    container_name: kintone_revproxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log:/var/log/nginx
      - ./certs/example.com.pem:/example.com.pem:ro
      - ./certs/example.com-key.pem:/example.com-key.pem:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=example.com
    command: ['nginx-debug', '-g', 'daemon off;']

